name: Publish docs

on:
  push:
    tags:
      - v*

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    env:
      TERM: dumb

    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material

      - uses: burrunan/gradle-cache-action@v1
        name: Setup Gradle cache
        with:
          save-local-build-cache: true
          save-gradle-dependencies-cache: true
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml

      - name: Generate docs
        run: ./generate_docs.sh

      - name: Build site
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
